version: '3.9'

services:
  nginx:
    container_name: '${CONTAINER_NAME}'
    image: '${PROJECT_NAME}/${IMAGE_NAME}:${BUILD_VERSION}'
    ulimits:
      nofile:
        soft: 3072
        hard: 4096
    build:
      context: '.'
      dockerfile: './containers/nginx/build/Dockerfile.prod'
      target: final
      args:
        NGINX_VERSION: '${NGINX_VERSION}'
        NGINX_HEADERS_MORE_VERSION: '${NGINX_HEADERS_MORE_VERSION}'
    ports:
        - "80:8080"
    environment:
      NGINX_ENVSUBST_TEMPLATE_DIR: /etc/nginx/templates
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/conf.d
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
