const finishedProducts = [
    {name: "eye contours", key: "eye", shortDesc: "Caffeine 10% + EGCG", imgName: "serum-CAFFEINE.png", completeName: "Anti-dark circles & Puffiness serum", paragraphsDescList: ["Akore Formulations has developed this serum to reduce the appearance of bluish dark circles and under-eye puffiness by stimulating blood and lymph circulation. Bags under the eyes are caused by an accumulation of water and fat.", "Deficient blood circulation in this area manifests itself in bluish-tinted dark circles. This serum, highly enriched with caffeine, stimulates blood microcirculation."], checkboxDescList: ["Helps reduce the appearance of puffiness and dark circles under the eyes", "Reduces the appearance of dark circles with a bluish or purplish tint", "Helps eliminate excess water for a smoother eye contour", "Helps slow the signs of skin aging", "Improves skin elasticity", "Reduces signs of fatigue"], ingredientParagraph: "Aqua (Water) • Caffeine • Epigallocatechin Gallate Glucoside (EGCG) • Span 60 • Tween 60 • Cholesterol • Vitamin E as d-alpha tocopherol • Glycerol • Xanthan Gum • Natural Preservative", howToUseParagraphsList: ["Apply a drop of Caffeine Serum under each eye, morning and night. Gently massage the area around the eyes, using circular movements to target puffiness.","We recommend using this caffeine serum for at least 4 weeks to observe its benefits. It will help to visibly reduce dark circles and puffiness, but for optimum results, this should be complemented by a healthy lifestyle, including sufficient hydration, adequate sleep and limiting alcohol consumption."], precautionsParagraphsList: ['Discontinue use if you feel discomfort or irritation.<br/>Avoid contact with eyes. In case of contact, rinse thoroughly with clean water.<br/>It is advisable to test patches before use. Keep out of reach of children.']},
    {name: "blemish-control", key: "blemish", shortDesc: "Glycolic Acid 10% + Bakuchiol 1%", imgName: "serum-GLYCOLIC-ACID.png", completeName: "Blemish-control & Exfoliating serum", paragraphsDescList: ["Akore Formulations has developed this serum to combat blackheads and dilated pores, for a smooth, even complexion. An uneven complexion can often result from the accumulation of dead cells on the skin's surface.", "Thanks to its high glycolic acid content, our serum acts by exfoliating dead cells and refining pores for smoother, more even skin. What's more, it offers a deep purifying action, effectively combating blackheads."], checkboxDescList:["Helps diminish the appearance of imperfections, without drying out the skin, and combats enlarged pores", "Helps reduce the appearance of blackheads and pimples by unclogging pores blocked by excess sebum", "Helps eliminate dead cells from the epidermal surface, promoting a smoother, more radiant complexion", "Stimulates cell renewal, helping to improve skin texture and reduce signs of aging"], ingredientParagraph: "Aqua (Water) • Glycolic Acid • Bakuchiol • Span 60 • Tween 60 • Cholesterol • Vitamin E as d-alpha tocopherol • Glycerol • Xanthan Gum • Natural Preservative.", howToUseParagraphsList: ["Use 3 to 4 drops of our glycolic acid serum on your face only in the evening. Massage gently in circular motions, taking care to avoid the eye area.", "Our serum contains glycolic acid, a type of alpha-hydroxy acid (AHA), which can make skin more susceptible to sun damage. It's crucial not to apply it in the morning and to protect yourself from the sun with a suitable sunscreen, while reducing UV exposure for a week after use, as the risk of sunburn is increased.", "A slight reddening of the skin is normal after the first few applications, as your skin adjusts to the acid. This effect diminishes with regular use. Be sure to shake the product well before each use. For best results, we suggest making glycolic acid serum part of your skincare routine for at least 4 weeks."], precautionsParagraphsList: ['Discontinue use if you feel discomfort or irritation.<br/>Avoid contact with eyes. In case of contact, rinse thoroughly with clean water.<br/>It is advisable to test patches before use. Keep out of reach of children.']},
    {name: "glow", key: "glow", shortDesc: "Vitamin C 15% + Hyaluronic Acid 1%", imgName: "serum-VITAMINE-C.png", completeName: "Glow & Brightening serum", paragraphsDescList: ["Akore Formulations has developed this serum to restore radiance to dull skin and prevent cutaneous photoaging.", "Insufficient sleep, stress and smoking are factors that stimulate the formation of free radicals, leading to the oxidation of epidermal cells and resulting in a dull complexion.", "Thanks to its high vitamin C content, this serum offers effective protection against this process."], checkboxDescList:["Illuminates dull & tired skin", "Restores radiance for preventing early signs of aging", "Fades acne scars and hyperpigmentation", "Firms and plumps", "Diminishes finelines and wrinkles"], ingredientParagraph: "Aqua (Water) • Vitamin C (Ethyl Ascorbic Acid ; Ascorbyl Glucoside) • Sodium Hyaluronate • Span 60 • Tween 60 • Cholesterol • Glycerol • Vitamin E as d-alpha tocopherol • Natural Preservative.", howToUseParagraphsList: ["Apply 3 to 4 drops to clean, dry skin each morning and evening. Gently massage into face and neck using circular motions. Then, follow with your moisturizer. For optimal results, we recommend to use this serum consistently for at least four weeks."], precautionsParagraphsList: ['Discontinue use if you feel discomfort or irritation.<br/>Avoid contact with eyes. In case of contact, rinse thoroughly with clean water.<br/>It is advisable to test patches before use. Keep out of reach of children.']},
    {name: "deep hydratation", key: "hydratation", shortDesc: "Hyaluronic Acid 3% + B5 2 %", imgName: "serum-HYALURONIC-ACID.png", completeName: "Deep hydration & Anti-aging", paragraphsDescList: ["Akore Formulations has developed this serum for hydrated, plumper, smoother skin by compensating for the natural depletion of hyaluronic acid in the skin", "Hyaluronic acid plays an essential role in maintaining the skin's hydration and preserving its soft, voluminous texture. The formula restores the skin's moisture levels throughout the day, and helps the skin retain moisture to plump up dry, dehydrated skin.", "To rebalance hydration, we use 3% plant hyaluronic acid in a blend of three different molecule sizes (high, medium and low molecular weight) helping to hydrate multiple layers of the skin's surface."], checkboxDescList:["Instantly moisturizes for softer & smoother skin", "Replenishes dry & dehydrated skin" , "Promotes skin's suppleness & elasticity" , "Reduces the appearance of fine lines & wrinkles" , "Helps protect skin against external agressions"], ingredientParagraph: "Aqua (Water) • Sodium Hyaluronate • Hydrolyzed Hyaluronic Acid • Acetylated Hyaluronic acid • Vitamin B5 as Panthenol • Span 60 • Tween 60 • Cholesterol • Glycerol.", howToUseParagraphsList: ["Place 3 to 4 drops of Hyaluronic Acid Serum on your clean, dry face, twice a day, morning and evening. Massage gently into your face and neck using circular movements. Follow with a moisturizing cream suited to your skin type.", "For extra hydration, mix a few drops of the serum directly with a small amount of moisturizer before applying to your skin.", "We recommend using the hyaluronic acid serum regularly for at least 4 weeks to fully observe its benefits."], precautionsParagraphsList: ['Discontinue use if you feel discomfort or irritation.<br/>Avoid contact with eyes. In case of contact, rinse thoroughly with clean water.<br/>It is advisable to test patches before use. Keep out of reach of children.']},
    {name: "even-complexion", key: "complexion", shortDesc: "Niacinamide 10 % + Zinc PCA 1%", imgName: "serum-NIACINAMIDE.png", completeName: "Even-Complexion & Anti-redness Serum", paragraphsDescList: ["Akore Formulations has developed this serum for blemish-prone skin. It will unify, smooth and optimize your skin's radiance with our water-based serum, enriched with 10% Niacinamide and 1% Zinc.", "This advanced treatment significantly improves skin smoothness while strengthening the skin barrier over time. Enjoy a high concentration of Niacinamide (vitamin B3) and Zinc PCA, designed to magnify your skin's appearance."], checkboxDescList:["Helps prevent imperfections", "Helps soothe redness while smoothing and refining skin texture", "Soothes irritation", "Promotes healing and tightens pores"], ingredientParagraph: "Aqua (Water) • Niacinamide • Zinc PCA • Span 60 • Tween 60 • Cholesterol • Glycerol • Xanthan Gum • Natural Preservative.", howToUseParagraphsList: ["Apply 3 to 4 drops to clean, dry skin each morning and evening. Gently massage into face and neck in circular motions", "For optimal results, we recommend to use this serum consistently for at least four weeks."], precautionsParagraphsList: ['Discontinue use of niacinamide-containing serum if you experience discomfort or irritation.<br/>Avoid contact with eyes. In case of contact, rinse thoroughly with clear water.<br/>Patch testing prior to use is advised. Keep out of reach of children.', 'It\'s important to note that our Niacinamide and Zinc PCA serum is not intended as a treatment for acne. For persistent acne-related conditions, we recommend consulting a healthcare professional to explore treatment options. Our formula is, however, compatible with anti-acne treatments, providing additional visible benefits for the skin.']},
];

const rawProducts = [
    {name: "glycolic acid", key: "glycolic", shortDesc: "Exfoliating", imgName: "serum-MP--GLYCOLIC-ACID.png"},
    {name: "hyaluronic acid", key: "hyaluronic", shortDesc: "Hydration & Anti-aging", imgName: "serum-MP--HYALURONIC-ACID.png"},
    {name: "bakuchiol", key: "bakuchiol", shortDesc: "Blemish-control", imgName: "serum-MP--BAKUCHIOL.png"},
    {name: "caffeine", key: "caffeine", shortDesc: "Eye contours", imgName: "serum-MP--CAFFEINE.png"},
    {name: "EGCG", key: "EGCG", shortDesc: "Glow & Anti-aging", imgName: "serum-MP--EGCG.png"},
    {name: "niacinamide", key: "niacinamide", shortDesc: "Hyaluronic Acid 3% + B5 2 %", imgName: "serum-MP--NIACINAMIDE.png"},
    {name: "vitamin C", key: "vitamin", shortDesc: "Blemish-control", imgName: "serum-MP--VITAMIN-C.png"},
    {name: "zinc", key: "zinc", shortDesc: "Healing & soothing", imgName: "serum-MP--ZINC.png"},
]

export function getFinishedProducts(){
    return finishedProducts;
}

export function getFinishedProductByKey(key){
    return finishedProducts.find(product => product.key === key);
}

export function getRawProducts(){
    return rawProducts;
}

export function getRawProductByKey(key){
    return rawProducts.find(product => product.key === key);
}